if(WIN32)
    find_program(GXX_EXECUTABLE g++)
    if(GXX_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${GXX_EXECUTABLE}")
    else()
        message(FATAL_ERROR "g++ not found in PATH")
    endif()
elseif(LINUX)
    find_program(GXX_EXECUTABLE gcc)
    if(GXX_EXECUTABLE)
        set(CMAKE_CXX_COMPILER "${GXX_EXECUTABLE}")
    else()
        message(FATAL_ERROR "gcc not found in PATH")
    endif()
endif()